[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install --prefix backend']

[phases.build]
cmds = ['echo "Backend ready for deployment"']

[start]
cmd = 'cd backend && node server.js'

[variables]
NODE_ENV = 'production'