const mongoose = require('mongoose');
require('dotenv').config();

// Your profiles data will go here
const profilesData = {

    "fren": {
        username: "fren",
        handle: "@0xfrenship",
        twitterHandle: "fren",
        bio: "progressive house connoisseur | only losers cry in the casino",
        followers: "90.3K",
        following: "1.8K",
        posts: "149.2k",
        image: "https://pbs.twimg.com/profile_images/1907915356112306176/nBAbB6N-_400x400.jpg",
        votes: 1070,
        marketCap: "$19.65k",
        change: "+0.77%",
        score: 1070,
        votesHistory: []
    },
    "Lotion Joe": {
        username: "Lotion Joe",
        handle: "@Lotion_joe",
        twitterHandle: "Lotion Joe",
        bio: "always building - access the private group here 👉 http://whop.com/lynk",
        followers: "1,543K",
        following: "1,287K",
        posts: "3,111K",
        image: "https://pbs.twimg.com/profile_images/1929858755023265792/3qpbU27u_400x400.jpg",
        votes: 1040,
        marketCap: "$20.50k",
        change: "-5.19%",
        score: 1040,
        votesHistory: []
    },
    "MoonBoyMaxi": {
        username: "MoonBoyMaxi",
        handle: "@Rothmus",
        twitterHandle: "Rothmus",
        bio: "Memes. Voluntaryism. Laissez-faire. Individualism. Propertarianism. Austrian Economics.",
        followers: "596.5K",
        following: "2,557",
        posts: "147.3K",
        image: "https://pbs.twimg.com/profile_images/1427434033290661891/hLTTZ5lt_400x400.jpg",
        votes: 977,
        marketCap: "$17.77k",
        change: "-2.11%",
        score: 977,
        votesHistory: []
    },
    "Jeremy": {
        username: "Jeremy",
        handle: "@Jeremyybtc",
        twitterHandle: "Jeremyybtc",
        bio: "unemployed (btc) since 17 | chief of vibes and imaginary money |",
        followers: "251.4K",
        following: "35.8K",
        posts: "15.2K",
        image: "https://pbs.twimg.com/profile_images/1823163289984991233/ettiw3_w_400x400.jpg",
        votes: 926,
        marketCap: "$10.25k",
        change: "+1.30%",
        score: 926,
        votesHistory: []
    },
    "Dior (victory arc)": {
        username: "Dior (victory arc)",
        handle: "@Dior100x",
        twitterHandle: "Dior100x",
        bio: "it will come back • it always does • yours truly •",
        followers: "98.5K",
        following: "528",
        posts: "22.2K",
        image: "https://pbs.twimg.com/profile_images/1933585366377762816/HMPG7vkn_400x400.jpg",
        votes: 925,
        marketCap: "$9.91k",
        change: "-0.56%",
        score: 925,
        votesHistory: []
    },
    "Tom": {
        username: "Tom",
        handle: "@SolportTom",
        twitterHandle: "SolportTom",
        bio: "Derugged",
        followers: "133.4K",
        following: "1.9K",
        posts: "6,250",
        image: "https://pbs.twimg.com/profile_images/1643347033573535747/MyGKYVX9_400x400.jpg",
        votes: 899,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 899,
        votesHistory: []
    },
    "sling (🐘,🐘)": {
        username: "sling (🐘,🐘)",
        handle: "@slingdeez",
        twitterHandle: "slingdeez",
        bio: "emotionally unstable",
        followers: "68.5K",
        following: "5.1K",
        posts: "88.5K",
        image: "https://pbs.twimg.com/profile_images/1948825625474564097/ehKuJCvg_400x400.jpg",
        votes: 877,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 877,
        votesHistory: []
    },
    "Sweep": {
        username: "Sweep",
        handle: "@0xSweep",
        twitterHandle: "0xSweep",
        bio: "degenerate digital broom | crypto since 17' | punk#1863 | advisor",
        followers: "206.2K",
        following: "18.4K",
        posts: "658.2K",
        image: "https://pbs.twimg.com/profile_images/1822955310459334657/59u8XJL3_400x400.jpg",
        votes: 856,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 856,
        votesHistory: []
    },
    "James Wynn 🐳": {
        username: "James Wynn 🐳",
        handle: "@JamesWynnReal",
        twitterHandle: "JamesWynnReal",
        bio: "high risk leverage trader / meme coin degen / called pepe at 600k market cap / Disclaimer: nothing I share is financial advice. Invest at your own risk. DYOR.",
        followers: "221.8K",
        following: "451",
        posts: "12.9K",
        image: "https://pbs.twimg.com/profile_images/1935578770586341376/V1MN4DBi_400x400.jpg",
        votes: 832,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 832,
        votesHistory: []
    },
    "Hydraze 🏴‍☠️ 🦜": {
        username: "Hydraze 🏴‍☠️ 🦜",
        handle: "@Hydraze420",
        twitterHandle: "@Hydraze420",
        bio: "Crypto Pirate. Founder:",
        followers: "136.5K",
        following: "3.5K",
        posts: "31.5K",
        image: "https://pbs.twimg.com/profile_images/1931474104684605440/TLMLjVgj_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "gake": {
        username: "gake",
        handle: "@Ga__ke",
        twitterHandle: "@Ga__ke",
        bio: "NOT Financial Advice | For Collabs (no token deals):",
        followers: "107.7K",
        following: "4,916K",
        posts: "21.3K",
        image: "https://pbs.twimg.com/profile_images/1943865492227469314/CbC7EvTA_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "dv": {
        username: "dv",
        handle: "@vibed333",
        twitterHandle: "@vibed333",
        bio: "BLOOM BOT",
        followers: "14.5K",
        following: "233",
        posts: "784",
        image: "https://pbs.twimg.com/profile_images/1757177002183073792/m7xCuBy0_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Smokez": {
        username: "@SmokezXBT",
        handle: "@SmokezXBT",
        twitterHandle: "Smokez",
        bio: "Him. CLFNF",
        followers: "912",
        following: "64.1K",
        posts: "18.1K",
        image: "https://pbs.twimg.com/profile_images/1810525044340076544/qnuUVmDb_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "gr3g": {
        username: "gr3g",
        handle: "@gr3gor14n",
        twitterHandle: "@gr3gor14n",
        bio: "toad - https://axiom.trade/@gr3g1 - dms here - http://t.me/Gr3g0r14n",
        followers: "5,305K",
        following: "31.6K",
        posts: "10.1K",
        image: "https://pbs.twimg.com/profile_images/1949000423328579584/-xiYpdiQ_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "Pandora": {
        username: "Pandora",
        handle: "@pandoraflips",
        twitterHandle: "@pandoraflips",
        bio: "i gamble @Scannoors @aimbotfnf",
        followers: "6.1K",
        following: "1.9K",
        posts: "6.3K",
        image: "https://pbs.twimg.com/profile_images/1929390228168728576/iqrOEDdd_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Beaver 🦁": {
        username: "Beaver 🦁",
        handle: "@beaverd",
        twitterHandle: "@beaverd",
        bio: "God's most retarded soldier",
        followers: "28.8K",
        following: "2.2K",
        posts: "12K",
        image: "https://pbs.twimg.com/profile_images/1939083138203836418/ed_4Ioxm_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "danny": {
        username: "danny",
        handle: "@0xSevere",
        twitterHandle: "@0xSevere",
        bio: "@splizzdaoxx",
        followers: "11K",
        following: "400",
        posts: "600",
        image: "https://pbs.twimg.com/profile_images/1947871032821366784/cOdbqx7L_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Latuche": {
        username: "Latuche",
        handle: "@Latuche95",
        twitterHandle: "@Latuche95",
        bio: "3x milady, 2x pudgy penguins, 2x bit bear",
        followers: "17.1K",
        following: "800",
        posts: "5K",
        image: "https://pbs.twimg.com/profile_images/1827136778467151872/tEaAhX1P_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "KADENOX": {
        username: "KADENOX",
        handle: "@kadenox",
        twitterHandle: "@kadenox",
        bio: "making it out @PadreApp partner @HighIQ_@TradeOnNova",
        followers: "5.8K",
        following: "470",
        posts: "570",
        image: "https://pbs.twimg.com/profile_images/1891693740445581312/Zr9F9g4G_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "jijo": {
        username: "jijo",
        handle: "@jijo_exe",
        twitterHandle: "@jijo_exe",
        bio: "likely in the trenches | http://t.me/jijosjournal",
        followers: "12.6K",
        following: "400",
        posts: "1.5K",
        image: "https://pbs.twimg.com/profile_images/1819429766828568576/wJCaFLgE_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "ozark": {
        username: "ozark",
        handle: "@ohzarke",
        twitterHandle: "@ohzarke",
        bio: "( -_•) ▄︻デ══━一 💥",
        followers: "10.7K",
        following: "800",
        posts: "1.6K",
        image: "https://pbs.twimg.com/profile_images/1874651192090845184/nZyK5ZMo_400x400.png",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "N’o": {
        username: "N’o",
        handle: "@Nosa1x",
        twitterHandle: "@Nosa1x",
        bio: "soon | @FadedFNF",
        followers: "1.4K",
        following: "181",
        posts: "2K",
        image: "https://pbs.twimg.com/profile_images/1917917207398432768/lULLs0NZ_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "aloh": {
        username: "aloh",
        handle: "@alohquant",
        twitterHandle: "@alohquant",
        bio: "trenches addict @AimbotFnF https://axiom.trade/@aoo",
        followers: "6.2K",
        following: "920",
        posts: "1K",
        image: "https://pbs.twimg.com/profile_images/1902805382436888576/_eCgZFQD_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "dean bulla (69)": {
        username: "dean bulla (69)",
        handle: "@deanbulla",
        twitterHandle: "@deanbulla",
        bio: "cynical optimist. trading magic internet beans. http://moonshot.money/DeanBulla **NFA**",
        followers: "112.9K",
        following: "27.6K",
        posts: "236.8K",
        image: "https://pbs.twimg.com/profile_images/1948351551287791616/cBdxeEyT_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "ignHail": {
        username: "ignHail",
        handle: "@ignHail",
        twitterHandle: "@ignHail",
        bio: "24/7 Grinding | @MorphosisFNF",
        followers: "2.3K",
        following: "400",
        posts: "200",
        image: "https://pbs.twimg.com/profile_images/1879192271540666368/ej_wC9iU_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Sebastian Orellana": {
        username: "Sebastian Orellana",
        handle: "@Saint_pablo123",
        twitterHandle: "@Saint_pablo123",
        bio: "Everything Will Come Into Fruition. Aka - young papi pablo. https://whop.com/tradersliquidityloungetrenches/ https://youtube.com/@SebOrellana",
        followers: "5K",
        following: "300",
        posts: "2100",
        image: "https://pbs.twimg.com/profile_images/1926850199336402944/Sk9y3Y3V_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Heyitsyolo": {
        username: "Heyitsyolo",
        handle: "@Heyitsyolotv",
        twitterHandle: "@Heyitsyolotv",
        bio: "THIS IS MY ONLY ACCOUNT @HEYITSYOLOTV",
        followers: "10.6K",
        following: "500",
        posts: "626",
        image: "https://pbs.twimg.com/profile_images/1911204710679261184/YitN6p3E_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "Mr. Frog, (Road to Redemption Arc)": {
        username: "Mr. Frog, (Road to Redemption Arc)",
        handle: "@TheMisterFrog",
        twitterHandle: "@TheMisterFrog",
        bio: "Some of us are going to make it.",
        followers: "130K",
        following: "1.6K",
        posts: "33.8K",
        image: "https://pbs.twimg.com/profile_images/1755441029371604992/wVBrT2Sv_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Orange": {
        username: "Orange",
        handle: "@OrangeSBS",
        twitterHandle: "@OrangeSBS",
        bio: "A trencherrrrrrrrr | Use my Axiom link for a 100x | @TrainersFNF",
        followers: "33.3K",
        following: "1.6K",
        posts: "4.5K",
        image: "https://pbs.twimg.com/profile_images/1944791978773721088/3jD3ZcY0_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "boogie": {
        username: "boogie",
        handle: "@boogiepnl",
        twitterHandle: "@boogiepnl",
        bio: "According to God's Will",
        followers: "7.5K",
        following: "600",
        posts: "1.6K",
        image: "https://pbs.twimg.com/profile_images/1945158933158502407/V4CFvERz_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

        "West": {
        username: "West",
        handle: "@ratwizardx",
        twitterHandle: "@ratwizardx",
        bio: "I stream everyday for 8 hours a day: https://kick.com/ratwizard no official tg",
        followers: "33.6K",
        following: "562",
        posts: "2.1K",
        image: "https://pbs.twimg.com/profile_images/1926585378653286400/KsJXMrUz_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "meechie": {
        username: "meechie",
        handle: "@973Meech",
        twitterHandle: "@973Meech",
        bio: "progressive house connoisseur | only losers cry in the casino",
        followers: "93.1K",
        following: "1.9K",
        posts: "149K",
        image: "https://pbs.twimg.com/profile_images/1875687765569916928/gA42pVfB_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Andrew Tate": {
        username: "Andrew Tate",
        handle: "@Cobratate",
        twitterHandle: "@Cobratate",
        bio: "Unmatched perspicacity coupled with sheer indefatigability makes me a feared opponent in any realm of human endeavour.  ",
        followers: "10.7M",
        following: "1.1k",
        posts: "31.5K",
        image: "https://pbs.twimg.com/profile_images/1887763323464146945/5HdM0_7C_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "groovy.eth": {
        username: "groovy.eth",
        handle: "@0xGroovy",
        twitterHandle: "@0xGroovy",
        bio: "NFA @notgroovy🐸🤡",
        followers: "33.3K",
        following: "6K",
        posts: "89.2K",
        image: "https://pbs.twimg.com/profile_images/1948717840707530752/Yz-MTzRL_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "til": {
        username: "til",
        handle: "@tilcrypto",
        twitterHandle: "@tilcrypto",
        bio: "http://discord.gg/solextraction",
        followers: "11.8K",
        following: "380",
        posts: "4.5K",
        image: "https://pbs.twimg.com/profile_images/1923335998278361088/J4LMORSv_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

        "goob": {
        username: "goob",
        handle: "@ifullclipp",
        twitterHandle: "@ifullclipp",
        bio: "I don’t actually full clip | http://t.me/goobscall ~ http://toshi.bet/r/goobsol",
        followers: "19.6K",
        following: "600",
        posts: "8.5K",
        image: "https://pbs.twimg.com/profile_images/1921118443052691457/HLY7GK6l_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Eric Cryptoman": {
        username: "Eric Cryptoman",
        handle: "@EricCryptoman",
        twitterHandle: "@EricCryptoman",
        bio: "Full-time ape since 2016. Shitcoin maxi🦄3x bear market survivor🐻More 100x calls than I can count🔮Sniper of leverage scalps🎯I dont see X DMs, TG pinned📌",
        followers: "260K",
        following: "3.6K",
        posts: "31.5K",
        image: "https://pbs.twimg.com/profile_images/1869889831880347648/XBGvOaoV_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Lexapro": {
        username: "Lexapro",
        handle: "@LexaproTrader",
        twitterHandle: "@LexaproTrader",
        bio: "#::::://// CRYPTO/ MEMECOINS - full time trader 🤺🤺🤺🤺🤺🤺🤺 my TG handle is @lexapro_trader NOT @lexaprotrader My TG channel is: https://t.me/lexaprosfeed",
        followers: "80K",
        following: "5.6K",
        posts: "43.9K",
        image: "https://pbs.twimg.com/profile_images/1762316875961442304/OvvzEDjJ_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "gainzy": {
        username: "gainzy",
        handle: "@gainzy222",
        twitterHandle: "@gainzy222",
        bio: "Building.",
        followers: "299K",
        following: "1.1K",
        posts: "27.6K",
        image: "https://pbs.twimg.com/profile_images/1763753850240983040/bg9hu_kW_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "orangie": {
        username: "orangie",
        handle: "@orangie",
        twitterHandle: "@orangie",
        bio: "@potionalpha @tradeonnova • crypto YouTuber • @uxento",
        followers: "305K",
        following: "9.6K",
        posts: "71K",
        image: "https://pbs.twimg.com/profile_images/1919076155690283009/6gLi-xyk_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Hsaka": {
        username: "Hsaka",
        handle: "@HsakaTrades",
        twitterHandle: "@HsakaTrades",
        bio: "• I trade, I drink your milkshake •",
        followers: "600K",
        following: "3.2K",
        posts: "23K",
        image: "https://pbs.twimg.com/profile_images/1690929913270792192/6n-PzBnB_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        
        "RookieXBT 🧲": {
        username: "RookieXBT 🧲",
        handle: "@RookieXBT",
        twitterHandle: "@RookieXBT",
        bio: "internet coins",
        followers: "490K",
        following: "1.6K",
        posts: "30K",
        image: "https://pbs.twimg.com/profile_images/1944768302271574016/mY1c4sjo_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "sugaR 🍬": {
        username: "sugaR 🍬",
        handle: "@suganarium",
        twitterHandle: "@suganarium",
        bio: "Just a degen who believes in something 🍹, @artspyre drinks on me, Tweets & RTs are not endorsements. DYOR, NFA.",
        followers: "85.3K",
        following: "11.7K",
        posts: "48.3K",
        image: "https://pbs.twimg.com/profile_images/1757857533803257856/57f2DcZi_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "bizzy": {
        username: "bizzy",
        handle: "@0xBiZzy",
        twitterHandle: "@0xBiZzy",
        bio: "LP GCR. Post-Rich Gorillionaire. Magical internet money connoisseur.",
        followers: "34.4K",
        following: "3.3K",
        posts: "57.7K",
        image: "https://pbs.twimg.com/profile_images/1753638166416789504/mtdOiLx8_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "jidn": {
        username: "jidn",
        handle: "@jidn_w",
        twitterHandle: "@jidn_w",
        bio: "@Pioneerfnf",
        followers: "13.6K",
        following: "500",
        posts: "1.2K",
        image: "https://pbs.twimg.com/profile_images/1775359484187037696/ojngbrSt_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "🔫": {
        username: "🔫",
        handle: "@Solshotta",
        twitterHandle: "@Solshotta",
        bio: "sol chain harvard graduate & high P individual Telegram: https://t.me/solshotta Youtube https://youtube.com/@Solshotta @PioneerFnf @TroupeFtm",
        followers: "25.4K",
        following: "700",
        posts: "640",
        image: "https://pbs.twimg.com/profile_images/1784713083950092288/gXwFoT_g_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "nyhrox": {
        username: "nyhrox",
        handle: "@nyhrox",
        twitterHandle: "@nyhrox",
        bio: "trader & fortnite world cup duo winner 🏆 | management@nyhroxofficiaI.com 📩 | @PioneerFNF",
        followers: "300K",
        following: "3.5K",
        posts: "7K",
        image: "https://pbs.twimg.com/profile_images/1878189429245825024/jXucBf43_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "polar": {
        username: "polar",
        handle: "@polarsterrr",
        twitterHandle: "@polarsterrr",
        bio: "trenches",
        followers: "38.3K",
        following: "1K",
        posts: "13.3K",
        image: "https://pbs.twimg.com/profile_images/1946419301633699840/XKllS7ug_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Cooker.hl | Kms.eth | Cooker": {
        username: "Cooker.hl | Kms.eth | Cooker",
        handle: "@CookerFlips",
        twitterHandle: "@CookerFlips",
        bio: "Founder @PastelAlpha DM @atomicfartt on TG for Biz ",
        followers: "119.4K",
        following: "3.6K",
        posts: "28.6K",
        image: "https://pbs.twimg.com/profile_images/1940993045870104576/h5MzwFqw_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "waddles": {
        username: "waddles",
        handle: "@waddles_eth",
        twitterHandle: "@waddles_eth",
        bio: "@PioneerFNF it's Waddles Wrld and you're just livin it in",
        followers: "31.5K",
        following: "160",
        posts: "1K",
        image: "https://pbs.twimg.com/profile_images/1946025529481494528/lExZKYHo_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "scooter": {
        username: "scooter",
        handle: "@imperooterxbt",
        twitterHandle: "@imperooterxbt",
        bio: "high lev pro trader, sometimes professional comedic Larp",
        followers: "116.6K",
        following: "2K",
        posts: "23.1K",
        image: "https://pbs.twimg.com/profile_images/1908297510256320512/ZfCHJgBE_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "Gorilla Capital (🦍,🦍)": {
        username: "Gorilla Capital (🦍,🦍)",
        handle: "@gorillacapsol",
        twitterHandle: "@gorillacapsol",
        bio: "Memecoin Quant.",
        followers: "28.7K",
        following: "2.2K",
        posts: "12.4K",
        image: "https://pbs.twimg.com/profile_images/1880191961354702848/z8dhUw3c_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "edward": {
        username: "edward",
        handle: "@jeetassassin",
        twitterHandle: "@jeetassassin",
        bio: "Crypto Pirate. Founder:",
        followers: "51K",
        following: "800",
        posts: "33.2K",
        image: "https://pbs.twimg.com/profile_images/1930587195330494464/f9IFFtrw_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Envy": {
        username: "Envy",
        handle: "@WhosEnvy",
        twitterHandle: "@WhosEnvy",
        bio: "https://t.me/EnvyAlpha | professional frontrunner |",
        followers: "58.9K",
        following: "9.5K",
        posts: "4.5K",
        image: "https://pbs.twimg.com/profile_images/1794978986528780288/dvu_OAqJ_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "geni": {
        username: "geni",
        handle: "@geniixzy",
        twitterHandle: "@geniixzy",
        bio: "Crypto Pirate. Founder:",
        followers: "66.7K",
        following: "7K",
        posts: "4K",
        image: "https://pbs.twimg.com/profile_images/1905361017749864449/PbkCb69J_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "Renaissance": {
        username: "Renaissance",
        handle: "@0xRenaissance",
        twitterHandle: "@0xRenaissance",
        bio: "Miracle maker.",
        followers: "23.1K",
        following: "1.8K",
        posts: "10K",
        image: "https://pbs.twimg.com/profile_images/1907847928791588864/iuk_aMB4_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "ً": {
        username: "ً",
        handle: "@CartiTheMenace",
        twitterHandle: "@CartiTheMenace",
        bio: "✦ ✧ 𝖞𝖔𝖚 𝖜𝖔𝖚𝖑𝖉𝖓’𝖙 𝖌𝖊𝖙 𝖎𝖙 ✧ ✦",
        followers: "15.3K",
        following: "1K",
        posts: "7.6K",
        image: "https://pbs.twimg.com/profile_images/1932976946620633089/nHphEunr_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "big bags bobby": {
        username: "big bags bobby",
        handle: "@bigbagsbobby",
        twitterHandle: "@bigbagsbobby",
        bio: "Trader - Trench Warrior - Building @MotusGuild⚔️",
        followers: "6.2K",
        following: "400K",
        posts: "2K",
        image: "https://pbs.twimg.com/profile_images/1894941962312077312/n1XCJvgS_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    }, 
       "absol": {
        username: "absol",
        handle: "@absolquant",
        twitterHandle: "@absolquant",
        bio: "fastest ct tracker for free http://discord.gg/solextraction",
        followers: "14K",
        following: "260K",
        posts: "1.4K",
        image: "https://pbs.twimg.com/profile_images/1925645249277218817/aqCBFytS_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "leens": {
        username: "leens",
        handle: "@leensx100",
        twitterHandle: "@leensx100",
        bio: "🇪🇸🇬🇧 professional gambler | @MotionFNF | @PotionAlpha  https://t.me/leenscooks",
        followers: "36.1K",
        following: "800",
        posts: "1.6K",
        image: "https://pbs.twimg.com/profile_images/1818713990588989440/VlX8E_8F_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "s": {
        username: "s",
        handle: "@runitbackghost",
        twitterHandle: "@runitbackghost",
        bio: "all i do is for my beautiful wife, my sweetheart eternal - crow",
        followers: "18.6K",
        following: "700",
        posts: "12.1K",
        image: "https://pbs.twimg.com/profile_images/1907294815081078784/KfZfapna_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
        "OGAntD": {
        username: "OGAntD",
        handle: "@0GAntD",
        twitterHandle: "@0GAntD",
        bio: "always in the arena @jeet_cap / @probablynothing binladen.sol",
        followers: "14.K",
        following: "900",
        posts: "5.5K",
        image: "https://pbs.twimg.com/profile_images/1946020920369254401/m2KNRjuS_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

         "SuspendedCap": {
        username: "SuspendedCap",
        handle: "@ContrarianCurse",
        twitterHandle: "@ContrarianCurse",
        bio: "Global LO PM || Head of the Semicap cult",
        followers: "8.8K",
        following: "800",
        posts: "4.6K",
        image: "https://pbs.twimg.com/profile_images/1900304446015610880/4heJRlp7_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

            "bhronos": {
        username: "bhronos",
        handle: "@bhronos",
        twitterHandle: "@bhronos",
        bio: "The more risk you take, the luckier you get • @miyuzx",
        followers: "45.2K",
        following: "2.1K",
        posts: "70.5K",
        image: "https://pbs.twimg.com/profile_images/1527356496014888960/blLMAf0S_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

           "Ansem 🧸💸": {
        username: "Ansem 🧸💸",
        handle: "@blknoiz06",
        twitterHandle: "@blknoiz06",
        bio: "coldest nigga breathing | trading @BullpenFi| poker @PlaySOPO | gambling @luckio | telegram @blknoiz06 | all other clone accounts are scams",
        followers: "740K",
        following: "8.4K",
        posts: "243K",
        image: "https://pbs.twimg.com/profile_images/1909437863592132608/R14kQm8j_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

         "alon": {
        username: "alon",
        handle: "@a1lon9",
        twitterHandle: "@a1lon9",
        bio: "co-founder @pumpdotfun",
        followers: "3.8K",
        following: "185K",
        posts: "5.7K",
        image: "https://pbs.twimg.com/profile_images/1875434258426187776/XUJTdd67_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

            "Game": {
        username: "Game",
        handle: "@game_for_one",
        twitterHandle: "@game_for_one",
        bio: "Risk on, risk off.",
        followers: "34K",
        following: "450",
        posts: "19K",
        image: "https://pbs.twimg.com/profile_images/1607722344432242689/m1XRdYV7_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

           "mog": {
        username: "mog",
        handle: "@10piecedawg",
        twitterHandle: "@10piecedawg",
        bio: "psyop everyone | @onchaintrench",
        followers: "34K",
        following: "1.4K",
        posts: "11.8K",
        image: "https://pbs.twimg.com/profile_images/1948538227520143361/BorZXG2Z_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

         "Cold": {
        username: "Cold",
        handle: "@cold_xyz",
        twitterHandle: "@cold_xyz",
        bio: "if you're reading this you're exit liquidity",
        followers: "44.5K",
        following: "384",
        posts: "43.6K",
        image: "https://pbs.twimg.com/profile_images/1945246739226562562/FEappdNt_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

          "spuno": {
        username: "spuno",
        handle: "@spunosounds",
        twitterHandle: "@spunosounds",
        bio: "✧ collecting magic internet money ✧ http://twitch.tv/spunosounds",
        followers: "46.1K",
        following: "1K",
        posts: "5.6K",
        image: "https://pbs.twimg.com/profile_images/1852443399271628801/QK1uy_j3_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

            "l1nk": {
        username: "l1nk",
        handle: "@l1nklul",
        twitterHandle: "@l1nklul",
        bio: "ex pro fn player 90k+ earnings | http://twitch.tv/l1nk",
        followers: "23.8K",
        following: "11.3K",
        posts: "1.9K",
        image: "https://pbs.twimg.com/profile_images/1894808141713559552/EpRND-gm_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

         "Iced": {
        username: "@Iced",
        handle: "@IcedKnife",
        twitterHandle: "@IcedKnife",
        bio: "$SOL gambling addict + low iq retard + partner @luckio https://axiom.trade/@iced https://luck.io/referral/iced",
        followers: "360K",
        following: "11.1k",
        posts: "86.9k",
        image: "https://pbs.twimg.com/profile_images/1650746818798444544/OaAb9GI0_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

            "Issa": {
        username: "Issa",
        handle: "@issathecooker",
        twitterHandle: "@issathecooker",
        bio: "t.me/issasthoughts",
        followers: "45.5K",
        following: "500",
        posts: "2.5K",
        image: "https://pbs.twimg.com/profile_images/1798875751309078528/jkRHRIrY_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

           "": {
        username: "",
        handle: "@0xRamonos",
        twitterHandle: "@0xRamonos",
        bio: "expert meme speculator.",
        followers: "177K",
        following: "3.8K",
        posts: "16.2K",
        image: "https://pbs.twimg.com/profile_images/1928531940342161409/RtYxPu-2_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

         "casino": {
        username: "casino",
        handle: "@casino616",
        twitterHandle: "@casino616",
        bio: "i buy and sell memecoins",
        followers: "57.2K",
        following: "1.2K",
        posts: "6.2K",
        image: "https://pbs.twimg.com/profile_images/1938817754917679104/ysUWGQMM_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

            "shah": {
        username: "shah",
        handle: "@shahh",
        twitterHandle: "@shahh",
        bio: "channel: https://t.me/shahlito | @rollbit partner | only telegram: shahwtf | I’m degenerate and shill my bags, tweets are not financial advice",
        followers: "388K",
        following: "17K",
        posts: "222K",
        image: "https://pbs.twimg.com/profile_images/1933513338639556608/QjCTIAkC_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

           "O G": {
        username: "O G",
        handle: "@OGshoots",
        twitterHandle: "@OGshoots",
        bio: "trader | actor | streamer @probablynothing | inventor @bothousela | https://toshi.bet/r/ogshoots",
        followers: "38.4K",
        following: "4.4K",
        posts: "33.5K",
        image: "https://pbs.twimg.com/profile_images/1927047758290055169/PMF3loRw_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

         "rektober": {
        username: "rektober",
        handle: "@rektober",
        twitterHandle: "@rektober",
        bio: "",
        followers: "94.7K",
        following: "1.1K",
        posts: "25K",
        image: "https://pbs.twimg.com/profile_images/1931377232800366592/b7zQoT5R_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

          "Tim": {
        username: "Tim",
        handle: "@timmpix1",
        twitterHandle: "@timmpix1",
        bio: "",
        followers: "9.7K",
        following: "1.5K",
        posts: "1K",
        image: "https://pbs.twimg.com/profile_images/1857579571857731584/gcD00AAj_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

              "Qwerty": {
        username: "Qwerty",
        handle: "@Quanterty",
        twitterHandle: "@Quanterty",
        bio: "Connoisseur",
        followers: "51.8K",
        following: "1.8K",
        posts: "8.7K",
        image: "https://pbs.twimg.com/profile_images/1915169391634767872/vXNJJulK_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  ".": {
        username: ".",
        handle: "@moneymaykah_",
        twitterHandle: "@moneymaykah_",
        bio: "made my teacher's salary in one trade.",
        followers: "70.2K",
        following: "730",
        posts: "11.2K",
        image: "https://pbs.twimg.com/profile_images/1926820675647320064/vVKYKTus_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "7": {
        username: "7",
        handle: "@Soloxbt",
        twitterHandle: "@Soloxbt",
        bio: "𝙏𝙝𝙞𝙨 𝙩𝙤𝙤 𝙎𝙝𝙖𝙡𝙡 𝙋𝙖𝙨𝙨 | dont copytrade | EXTRACTOR",
        followers: "14K",
        following: "300",
        posts: "600",
        image: "https://pbs.twimg.com/profile_images/1947826429187555330/9r-E8Lmn_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "threadguy": {
        username: "threadguy",
        handle: "@notthreadguy",
        twitterHandle: "@notthreadguy",
        bio: "skeptically optimistic @probablynothing @monad_xyz @phantom",
        followers: "319K",
        following: "15.5K",
        posts: "152K",
        image: "https://pbs.twimg.com/profile_images/1920651894982066176/ssOaEU8k_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "✰": {
        username: "✰",
        handle: "@redwithbag",
        twitterHandle: "@redwithbag",
        bio: "https://nova.trade/@red",
        followers: "37K",
        following: "300",
        posts: "36K",
        image: "https://pbs.twimg.com/profile_images/1916325806265286656/DaJ1hl7Y_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "ferb": {
        username: "ferb",
        handle: "@ferbsol",
        twitterHandle: "@ferbsol",
        bio: "a bittersweet success and a hopeful future.",
        followers: "30.6K",
        following: "550K",
        posts: "4.5K",
        image: "https://pbs.twimg.com/profile_images/1760274165070798848/f5V5qbs9_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Jakey": {
        username: "Jakey",
        handle: "@SolJakey",
        twitterHandle: "@SolJakey",
        bio: "What a time to be alive | @SUPERBASEDD | @bonkbot_io ( https://app.bonkbot.io/@jakey ) | @luckio",
        followers: "200K",
        following: "6.7K",
        posts: "55.6K",
        image: "https://pbs.twimg.com/profile_images/1874210663431573504/PkUwgxiN_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Cented 🇨🇦": {
        username: "Cented 🇨🇦",
        handle: "@Cented7",
        twitterHandle: "@Cented7",
        bio: "business inquiries: @bloomyoki centedbiz@gmail.com | https://youtube.com/@cented1189",
        followers: "444K",
        following: "2.8K",
        posts: "15.5K",
        image: "https://pbs.twimg.com/profile_images/1889750546791165952/vPbYBRtF_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Daumen": {
        username: "Daumen",
        handle: "@daumeneth",
        twitterHandle: "@daumeneth",
        bio: "From Nothing to Something. Trading on @tradewithPhoton",
        followers: "103K",
        following: "700",
        posts: "22K",
        image: "https://pbs.twimg.com/profile_images/1934771920781889538/KcuioX5p_400x400.jpg",
        votes: 799,
        marketCap: "$100K",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Dan176": {
        username: "Dan176",
        handle: "@176Dan",
        twitterHandle: "@176Dan",
        bio: "I get rugged by Pumpfun devs | @AxiomExchange& @shufflecom partner",
        followers: "35K",
        following: "400",
        posts: "15K",
        image: "https://pbs.twimg.com/profile_images/1885173397006450688/Mji3aig2_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Loopierr": {
        username: "Loopierr",
        handle: "@Loopierr",
        twitterHandle: "@Loopierr",
        bio: "We're all gonna make it bros 🤝 Partner @TradewithPhoton",
        followers: "14K",
        following: "1K",
        posts: "5.6K",
        image: "https://pbs.twimg.com/profile_images/1820609315524284416/vY1o9pFR_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Pyro": {
        username: "Pyro",
        handle: "@PyroNFT",
        twitterHandle: "@PyroNFT",
        bio: "On-chain Maxing",
        followers: "70K",
        following: "5K",
        posts: "7K",
        image: "https://pbs.twimg.com/profile_images/1788715552317558784/EK4eQtAU_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "CTM": {
        username: "CTM",
        handle: "@CryptoTalkMan",
        twitterHandle: "@CryptoTalkMan",
        bio: "Full time degen | Community guy | My thoughts and tweets are not financial advice",
        followers: "82K",
        following: "600",
        posts: "21K",
        image: "https://pbs.twimg.com/profile_images/1928661622635053056/OzqbQ3Uk_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Wulf 🐺": {
        username: "Wulf 🐺",
        handle: "@wulfcryptox",
        twitterHandle: "@wulfcryptox",
        bio: "My thoughts and tweets are not financial advice || dropping 100x calls here: http://t.me/wulfcryptocalls (only reply to DMs in TG)",
        followers: "40K",
        following: "2.5K",
        posts: "10K",
        image: "https://pbs.twimg.com/profile_images/1844141709984399361/_LciyBo2_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "wrld": {
        username: "wrld",
        handle: "@wrld_sol",
        twitterHandle: "@wrld_sol",
        bio: "*rarely checks dm’s*",
        followers: "40K",
        following: "4K",
        posts: "19K",
        image: "https://pbs.twimg.com/profile_images/1916905830261116928/X0CMKJSS_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "based16z": {
        username: "based16z",
        handle: "@based16z",
        twitterHandle: "@based16z",
        bio: "Creative Director",
        followers: "96K",
        following: "300",
        posts: "1K",
        image: "https://pbs.twimg.com/profile_images/1797820768396402688/stXcDcyP_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "him": {
        username: "him",
        handle: "@himgajria",
        twitterHandle: "@himgajria",
        bio: "Not financial advice.",
        followers: "101K",
        following: "2.2K",
        posts: "10K",
        image: "https://pbs.twimg.com/profile_images/1623269492607295488/Rh2iAjMN_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Jeets": {
        username: "Jeets",
        handle: "@ieatjeets",
        twitterHandle: "@ieatjeets",
        bio: "If you don’t see the asymmetric trade, you are the asymmetric trade. // Retarded Visionary. Intern.",
        followers: "28K",
        following: "1K",
        posts: "27K",
        image: "https://pbs.twimg.com/profile_images/1945601188184924160/RGEhQCk1_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "DLN": {
        username: "DLN",
        handle: "@xbtDLN",
        twitterHandle: "@xbtDLN",
        bio: "Jesus | Trading | TikTok Shop | Business | Economics | Every Man Wasn’t Made to Rule Nations",
        followers: "35K",
        following: "1K",
        posts: "30K",
        image: "https://pbs.twimg.com/profile_images/1717316147333246977/bQ0TLlyR_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "blanc": {
        username: "blanc",
        handle: "@blancxbt",
        twitterHandle: "@blancxbt",
        bio: "don’t take cat too seriously",
        followers: "25K",
        following: "1K",
        posts: "33K",
        image: "https://pbs.twimg.com/profile_images/1744265051920289792/s3-BTHX4_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Hugo Fartingale": {
        username: "Hugo Fartingale",
        handle: "@HugoMartingale",
        twitterHandle: "@HugoMartingale",
        bio: "inventor of the martingale strategy, intern @polymarket",
        followers: "25K",
        following: "2.6K",
        posts: "3K",
        image: "https://pbs.twimg.com/profile_images/1794879828673404928/QXoysakL_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Bounty": {
        username: "Bounty",
        handle: "@solbountyy",
        twitterHandle: "@solbountyy",
        bio: "gambler",
        followers: "48K",
        following: "1.1K",
        posts: "40K",
        image: "https://pbs.twimg.com/profile_images/1916260192427151360/8wxh2u60_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "": {
        username: "",
        handle: "@SolLunix",
        twitterHandle: "@SolLunix",
        bio: "content creator | streamer | twin account @LunixTwin partners @luckio @solpotcom @rainbetcom @flipdotmeme @glydegg",
        followers: "67K",
        following: "6.8K",
        posts: "28K",
        image: "https://pbs.twimg.com/profile_images/1907259314915414016/IQFxSk4j_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Doc": {
        username: "Doc",
        handle: "@docXBT",
        twitterHandle: "@docXBT",
        bio: "Perpetual Student l @TheParagonGrp Price Action ▫ Trends ▫ Orderflow",
        followers: "40K",
        following: "250",
        posts: "24K",
        image: "https://pbs.twimg.com/profile_images/1938307216978644992/n_4KKr_0_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Cred": {
        username: "Cred",
        handle: "@CryptoCred",
        twitterHandle: "@CryptoCred",
        bio: "Always trader, often shitposter, sometimes educator. @breakoutprop",
        followers: "704K",
        following: "1.1K",
        posts: "27K",
        image: "https://pbs.twimg.com/profile_images/1444398863268339717/2jQUsbjB_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },

                  "Pierre": {
        username: "Pierre",
        handle: "@pierre_crypt0",
        twitterHandle: "@pierre_crypt0",
        bio: "@TheHavenCrypto- NFA - just shitposting and sharing some thoughts about markets sometimes http://youtube.com/@pierre_crypt0",
        followers: "204K",
        following: "400",
        posts: "170K",
        image: "https://pbs.twimg.com/profile_images/1850886698567155712/89uxAOFF_400x400.jpg",
        votes: 799,
        marketCap: "$9.74k",
        change: "+0.66%",
        score: 799,
        votesHistory: []
    },
};

// Schema definition (must match server.js schema)
const profileSchema = new mongoose.Schema({
    username: String,
    handle: String,
    twitterHandle: String,
    bio: String,
    followers: String,
    following: String,
    posts: String,
    image: String,
    marketCap: String,
    change: String,
    votes: { type: Number, default: 0 },
    score: { type: Number, default: 0 },
    battleWins: { type: Number, default: 0 },
    battleLosses: { type: Number, default: 0 },
    chadVotes: { type: Number, default: 0 },
    jeetVotes: { type: Number, default: 0 },
    votesHistory: [{ timestamp: Date, voterId: String }]
});

const Profile = mongoose.model('Profile', profileSchema);

async function seedDatabase() {
    try {
        console.log('Connecting to MongoDB...');
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');
        
        // Clear existing profiles
        await Profile.deleteMany({});
        console.log('Cleared existing profiles');
        
        // Convert profiles object to array and add default values
        const profiles = Object.values(profilesData).map(profile => ({
            ...profile,
            votes: profile.votes || 799,
            score: profile.score || 799,
            battleWins: 0,
            battleLosses: 0,
            chadVotes: Math.floor(Math.random() * 1000) + 100,
            jeetVotes: Math.floor(Math.random() * 100) + 10,
            votesHistory: []
        }));
        
        // Insert all profiles
        await Profile.insertMany(profiles);
        console.log(`Seeded ${profiles.length} profiles successfully!`);
        
        // Close connection and exit
        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error);
        process.exit(1);
    }
}

// Run the seed function
seedDatabase();